//User actions
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';

export const SET_USER_FROM_TOKEN = 'SET_USER_FROM_TOKEN';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const API_LOADED = 'API_LOADED';
export const API_LOADING = 'API_LOADING';

export const LOGOUT_USER = 'LOGOUT_USER';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const SIGNUP_TEAM_MEMBER_ERROR = 'SIGNUP_TEAM_MEMBER_ERROR';
export const SIGNUP_TEAM_MEMBER_SUCCESS = 'SIGNUP_TEAM_MEMBER_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const SET_USER_PHONE = 'SET_USER_PHONE';

//Header actions
export const CUSTOM_HEADER_TITLE = 'CUSTOM_HEADER_TITLE';

export const OPEN_SIGNUP_MODAL = 'OPEN_SIGNUP_MODAL';
export const CLOSE_SIGNUP_MODAL = 'CLOSE_SIGNUP_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';

//City actions
export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR';

export const GET_AREAS = 'GET_AREAS';
export const GET_AREAS_SUCCESS = 'GET_AREAS_SUCCESS';
export const GET_AREAS_ERROR = 'GET_AREAS_ERROR';
export const SET_PROJECT_SEARCH = 'SET_PROJECT_SEARCH';
export const REMOVE_AREAS = 'REMOVE_AREAS';
export const SET_SEARCH_AREAS = 'SET_SEARCH_AREAS';


export const GET_GRID = 'GET_GRID';
export const GET_GRID_SUCCESS = 'GET_GRID_SUCCESS';
export const GET_GRID_ERROR = 'GET_GRID_ERROR';

//Property actions
export const IMAGE_UPLOAD = 'IMAGE_UPLOAD';
export const IMAGE_UPLOAD_PROGRESS = 'IMAGE_UPLOAD_PROGRESS';
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_REMOVE = 'REMOVE_IMAGE';
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR';
export const SAVE_IMAGE_PROMISE = 'SAVE_IMAGE_PROMISE';
export const IMAGE_COVER_PHOTO = 'IMAGE_COVER_PHOTO';

export const BLOCK_PROPERTY_SAVE = 'BLOCK_PROPERTY_SAVE';
export const UNBLOCK_PROPERTY_SAVE = 'UNBLOCK_PROPERTY_SAVE';
export const SAVE_PROPERTY = 'SAVE_PROPERTY';
export const SAVE_PROPERTY_SUCCESS = 'SAVE_PROPERTY_SUCCESS';
export const NOT_ENOUGH_CREDITS = 'NOT_ENOUGH_CREDITS';
export const SAVE_PROPERTY_ERROR = 'SAVE_PROPERTY_ERROR';

export const SET_PROPERTY_SEARCH_QUERY = 'SET_PROPERTY_SEARCH_QUERY';

export const SET_CANCEL_TOKEN = 'SET_CANCEL_TOKEN';

export const SEARCH_PROPERTY = 'SEARCH_PROPERTY';
export const SEARCH_PROPERTY_SUCCESS = 'SEARCH_PROPERTY_SUCCESS';
export const SEARCH_PROPERTY_ERROR = 'SEARCH_PROPERTY_ERROR';
export const SET_CURRENCY_RATES = 'SET_CURRENCY_RATES';

export const CURRENCY_CHANGE = 'CURRENCY_CHANGE';
export const UNIT_CHANGE = 'UNIT_CHANGE';
export const NOTIFICATION_READ = 'NOTIFICATION_READ';
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
export const SET_PROPERTY_SEARCH_FOOTER = 'SET_PROPERTY_SEARCH_FOOTER';

export const SEARCH_NO_PROPERTY_SUCCESS = 'SEARCH_NO_PROPERTY_SUCCESS'
export const FILTER_MODAL_CHANGE = 'FILTER_MODAL_CHANGE'
export const SET_PREBOOT_FLAG = 'SET_PREBOOT_FLAG'
export const SET_MOBILE_FLAG = 'SET_MOBILE_FLAG'

